from __future__ import annotations

from typing import Any

from app.core.json_utils import to_pretty_json


def research_prompt(job: dict[str, Any]) -> str:
    return f"""
You are the Research Agent for Pleopod, an AI-generated Tech podcast product.

Create a research dossier for this podcast topic:
Topic: {job["topic"]}
Category: {job["category"]}
Audience: {job["audience"]}
Language: {job["language"]}

Rules:
- Use recent, authentic, high-quality sources.
- Prefer primary sources: official docs, company posts, papers, public filings,
  and regulator or government sources.
- Use reputable journalism only when primary sources are unavailable.
- Do not invent facts, dates, numbers, product names, or quotes.
- Separate confirmed facts from analysis.
- Return JSON only.

JSON shape:
{{
  "summary": "short factual dossier summary",
  "key_points": ["point"],
  "open_questions": ["question"],
  "sources": [
    {{
      "url": "https://...",
      "title": "source title",
      "publisher": "publisher",
      "author": "author or null",
      "published_at": "ISO datetime or null",
      "source_tier": "A or B or C",
      "credibility_score": 0.0,
      "notes": "why source matters"
    }}
  ],
  "claims": [
    {{
      "claim_text": "atomic factual claim",
      "source_urls": ["https://..."],
      "verification_status": "supported",
      "confidence": 0.0,
      "notes": "context or caveat"
    }}
  ]
}}
""".strip()


def research_review_prompt(research: Any) -> str:
    return f"""
You are the Research Review Agent.
Verify and repair this research dossier before any script is written.

Tasks:
- Check whether claims are supported by sources.
- Mark unsupported or weakly supported claims.
- Improve claims when they are vague or misleading.
- Keep only claims useful for a factual Tech podcast.
- Return JSON only.

Input research:
{to_pretty_json(research)}

JSON shape:
{{
  "verdict": "approved | needs_more_research | rejected",
  "score": 0.0,
  "issues": ["issue"],
  "fixed_claims": [
    {{
      "claim_text": "atomic factual claim",
      "source_urls": ["https://..."],
      "verification_status": "supported | unsupported | misleading | needs_context",
      "confidence": 0.0,
      "notes": "review note"
    }}
  ],
  "review_summary": "human-readable review"
}}
""".strip()


def script_prompt(job: dict[str, Any], memory_md: str, claims: Any) -> str:
    return f"""
You are the Podcast Script Agent for Pleopod.

Write a factual, conversational two-speaker Tech podcast script.
It must be ready for Gemini 3.1 Flash TTS.

Topic: {job["topic"]}
Audience: {job["audience"]}
Target duration seconds: {job["target_duration_seconds"]}
Language: {job["language"]}
Tone: {job["tone"]}

TTS rules:
- Use exactly two speakers.
- Speaker names must be stable and simple.
- Keep the transcript clean: no markdown tables, no citations spoken aloud, no URLs in dialogue.
- Keep factual claims grounded in the claim bank.
- Use natural conversational turns.
- Include subtle audio tags only when useful, like [thoughtful], [curious], [short pause].
- Do not mention that this was generated by AI.
- Return JSON only.

Research memory:
{memory_md}

Approved claim bank:
{to_pretty_json(claims)}

JSON shape:
{{
  "title": "episode title",
  "slug": "url-safe-slug",
  "summary": "short summary",
  "description": "app-ready description",
  "speakers": [
    {{"name": "Arman", "role": "Host", "voice_name": "Charon", "style": "clear, warm"}},
    {{"name": "Maya", "role": "Analyst", "voice_name": "Puck", "style": "curious, energetic"}}
  ],
  "transcript": "TTS the following conversation between Arman and Maya:\\n\\n...",
  "used_claims": ["claim text"]
}}
""".strip()


def verification_prompt(script: Any, claims: Any) -> str:
    return f"""
You are the Fact Verification Agent. Review the podcast script line by line.

Tasks:
- Confirm every factual claim against the claim bank.
- Fix unsupported, misleading, or overconfident lines.
- Preserve a natural podcast voice.
- Return JSON only.

Script:
{to_pretty_json(script)}

Claim bank:
{to_pretty_json(claims)}

JSON shape:
{{
  "verdict": "approved | fixed | rejected",
  "score": 0.0,
  "issues": ["issue"],
  "fixed_transcript": "full fixed transcript or null",
  "line_checks": [
    {{
      "line": "speaker line",
      "claim": "claim or null",
      "verdict": "supported | unsupported | misleading | needs_context | non_factual",
      "source_urls": ["https://..."],
      "fix": "fixed line or null"
    }}
  ]
}}
""".strip()


def thumbnail_prompt(script: Any) -> str:
    return f"""
Create a premium podcast thumbnail for a Tech podcast episode.

Episode title: {script.get("title")}
Summary: {script.get("summary")}

Direction:
- Modern editorial tech visual.
- Strong focal point.
- No fake logos.
- No unreadable tiny text.
- Suitable for a podcast app card.
- Avoid clickbait.
- Use high contrast and clean composition.
""".strip()
